// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/state/profile/profile_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i3;
import 'package:wanderer_frontend/data/models/trip_models.dart' as _i7;
import 'package:wanderer_frontend/data/models/user_models.dart' as _i2;
import 'package:wanderer_frontend/data/repositories/profile_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePageResponse_1<T> extends _i1.SmartFake
    implements _i3.PageResponse<T> {
  _FakePageResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfile> getMyProfile() => (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getMyProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserProfile>);

  @override
  _i5.Future<_i2.UserProfile> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i5.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i5.Future<_i2.UserProfile>);

  @override
  _i5.Future<String> updateProfile(_i2.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadAvatar(
    List<int>? fileBytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            fileBytes,
            fileName,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              fileBytes,
              fileName,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #deleteAvatar,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i3.PageResponse<_i7.Trip>> getMyTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i3.PageResponse<_i7.Trip>>.value(
            _FakePageResponse_1<_i7.Trip>(
          this,
          Invocation.method(
            #getMyTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i3.PageResponse<_i7.Trip>>);

  @override
  _i5.Future<_i3.PageResponse<_i7.Trip>> getUserTrips(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTrips,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i3.PageResponse<_i7.Trip>>.value(
            _FakePageResponse_1<_i7.Trip>(
          this,
          Invocation.method(
            #getUserTrips,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i3.PageResponse<_i7.Trip>>);

  @override
  _i5.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getCurrentUsername() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUsername,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> refreshUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #refreshUserDetails,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
