// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/widgets/sso_callback_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:wanderer_frontend/data/models/auth_models.dart' as _i2;
import 'package:wanderer_frontend/data/repositories/auth_repository.dart'
    as _i3;
import 'package:wanderer_frontend/data/services/sso/sso_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterPendingResponse_0 extends _i1.SmartFake
    implements _i2.RegisterPendingResponse {
  _FakeRegisterPendingResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> login(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.RegisterPendingResponse> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.RegisterPendingResponse>.value(
            _FakeRegisterPendingResponse_0(
          this,
          Invocation.method(
            #register,
            [
              username,
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.RegisterPendingResponse>);

  @override
  _i4.Future<void> verifyEmail(String? token) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> requestPasswordReset(String? email) => (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completePasswordReset(
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completePasswordReset,
          [
            token,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completeSsoLogin(
    String? code,
    String? codeVerifier,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [
            code,
            codeVerifier,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SsoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSsoService extends _i1.Mock implements _i5.SsoService {
  MockSsoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Uri buildAuthorizationUri({
    required _i2.SsoProvider? provider,
    required String? returnTo,
    required String? codeChallenge,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildAuthorizationUri,
          [],
          {
            #provider: provider,
            #returnTo: returnTo,
            #codeChallenge: codeChallenge,
          },
        ),
        returnValue: _FakeUri_1(
          this,
          Invocation.method(
            #buildAuthorizationUri,
            [],
            {
              #provider: provider,
              #returnTo: returnTo,
              #codeChallenge: codeChallenge,
            },
          ),
        ),
      ) as Uri);

  @override
  String webReturnUri() => (super.noSuchMethod(
        Invocation.method(
          #webReturnUri,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #webReturnUri,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> savePendingVerifier(String? verifier) => (super.noSuchMethod(
        Invocation.method(
          #savePendingVerifier,
          [verifier],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> takePendingVerifier() => (super.noSuchMethod(
        Invocation.method(
          #takePendingVerifier,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
