// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/state/trip_plan_detail/trip_plan_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wanderer_frontend/data/client/google_directions_api_client.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GoogleDirectionsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDirectionsApiClient extends _i1.Mock
    implements _i2.GoogleDirectionsApiClient {
  MockGoogleDirectionsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getRoutePolyline(List<_i4.LatLng>? points) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoutePolyline,
          [points],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i2.DirectionsResult?> getRouteWithPoints(
          List<_i4.LatLng>? points) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRouteWithPoints,
          [points],
        ),
        returnValue: _i3.Future<_i2.DirectionsResult?>.value(),
      ) as _i3.Future<_i2.DirectionsResult?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
