// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wanderer_frontend/data/client/auth/auth_client.dart' as _i5;
import 'package:wanderer_frontend/data/client/query/user_query_client.dart'
    as _i7;
import 'package:wanderer_frontend/data/models/auth_models.dart' as _i2;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i3;
import 'package:wanderer_frontend/data/models/user_models.dart' as _i4;
import 'package:wanderer_frontend/data/storage/token_storage.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterPendingResponse_1 extends _i1.SmartFake
    implements _i2.RegisterPendingResponse {
  _FakeRegisterPendingResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePageResponse_2<T> extends _i1.SmartFake
    implements _i3.PageResponse<T> {
  _FakePageResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i4.UserProfile {
  _FakeUserProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthClient extends _i1.Mock implements _i5.AuthClient {
  MockAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthResponse> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<_i2.RegisterPendingResponse> register(
          _i2.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i6.Future<_i2.RegisterPendingResponse>.value(
            _FakeRegisterPendingResponse_1(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.RegisterPendingResponse>);

  @override
  _i6.Future<_i2.AuthResponse> verifyEmail(_i2.VerifyEmailRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [request],
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #verifyEmail,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.AuthResponse> refresh(_i2.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [request],
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #refresh,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<void> initiatePasswordReset(_i2.PasswordResetRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiatePasswordReset,
          [request],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> completePasswordReset(_i2.PasswordResetRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #completePasswordReset,
          [request],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> changePassword(_i2.PasswordChangeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [request],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [UserQueryClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserQueryClient extends _i1.Mock implements _i7.UserQueryClient {
  MockUserQueryClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.PageResponse<_i4.UserProfile>> getAllUsers({
    int? page = 0,
    int? size = 20,
    String? sort = 'username',
    String? direction = 'asc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
            #direction: direction,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserProfile>>.value(
            _FakePageResponse_2<_i4.UserProfile>(
          this,
          Invocation.method(
            #getAllUsers,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
              #direction: direction,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserProfile>>);

  @override
  _i6.Future<_i4.UserProfile> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i6.Future<_i4.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i6.Future<_i4.UserProfile>);

  @override
  _i6.Future<_i4.UserProfile> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i6.Future<_i4.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserByUsername,
            [username],
          ),
        )),
      ) as _i6.Future<_i4.UserProfile>);

  @override
  _i6.Future<_i4.UserProfile> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i4.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UserProfile>);

  @override
  _i6.Future<_i3.PageResponse<_i4.Friendship>> getFriends({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriends,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.Friendship>>.value(
            _FakePageResponse_2<_i4.Friendship>(
          this,
          Invocation.method(
            #getFriends,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.Friendship>>);

  @override
  _i6.Future<List<_i4.FriendRequest>> getReceivedFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedFriendRequests,
          [],
        ),
        returnValue:
            _i6.Future<List<_i4.FriendRequest>>.value(<_i4.FriendRequest>[]),
      ) as _i6.Future<List<_i4.FriendRequest>>);

  @override
  _i6.Future<List<_i4.FriendRequest>> getSentFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentFriendRequests,
          [],
        ),
        returnValue:
            _i6.Future<List<_i4.FriendRequest>>.value(<_i4.FriendRequest>[]),
      ) as _i6.Future<List<_i4.FriendRequest>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserFollow>> getFollowing({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserFollow>>.value(
            _FakePageResponse_2<_i4.UserFollow>(
          this,
          Invocation.method(
            #getFollowing,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserFollow>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserFollow>> getFollowers({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserFollow>>.value(
            _FakePageResponse_2<_i4.UserFollow>(
          this,
          Invocation.method(
            #getFollowers,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserFollow>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserFollow>> getUserFollowing(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowing,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserFollow>>.value(
            _FakePageResponse_2<_i4.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowing,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserFollow>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserFollow>> getUserFollowers(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowers,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserFollow>>.value(
            _FakePageResponse_2<_i4.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowers,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserFollow>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.Friendship>> getUserFriends(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFriends,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.Friendship>>.value(
            _FakePageResponse_2<_i4.Friendship>(
          this,
          Invocation.method(
            #getUserFriends,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.Friendship>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserProfile>> getDiscoverableUsers({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoverableUsers,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserProfile>>.value(
            _FakePageResponse_2<_i4.UserProfile>(
          this,
          Invocation.method(
            #getDiscoverableUsers,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserProfile>>);

  @override
  _i6.Future<_i3.PageResponse<_i4.UserRelationship>> getAssociatedUsers(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssociatedUsers,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i6.Future<_i3.PageResponse<_i4.UserRelationship>>.value(
            _FakePageResponse_2<_i4.UserRelationship>(
          this,
          Invocation.method(
            #getAssociatedUsers,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i6.Future<_i3.PageResponse<_i4.UserRelationship>>);
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i8.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> reloadFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #reloadFromDisk,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
    required String? tokenType,
    required int? expiresIn,
    String? userId,
    String? username,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #tokenType: tokenType,
            #expiresIn: expiresIn,
            #userId: userId,
            #username: username,
            #displayName: displayName,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getTokenType() => (super.noSuchMethod(
        Invocation.method(
          #getTokenType,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getUsername() => (super.noSuchMethod(
        Invocation.method(
          #getUsername,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getDisplayName() => (super.noSuchMethod(
        Invocation.method(
          #getDisplayName,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> saveDisplayName(String? displayName) => (super.noSuchMethod(
        Invocation.method(
          #saveDisplayName,
          [displayName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getAvatarUrl() => (super.noSuchMethod(
        Invocation.method(
          #getAvatarUrl,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> saveAvatarUrl(String? avatarUrl) => (super.noSuchMethod(
        Invocation.method(
          #saveAvatarUrl,
          [avatarUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isAccessTokenExpired() => (super.noSuchMethod(
        Invocation.method(
          #isAccessTokenExpired,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
