// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:wanderer_frontend/data/client/command/user_command_client.dart'
    as _i6;
import 'package:wanderer_frontend/data/client/query/user_query_client.dart'
    as _i4;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i2;
import 'package:wanderer_frontend/data/models/user_models.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserQueryClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserQueryClient extends _i1.Mock implements _i4.UserQueryClient {
  MockUserQueryClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PageResponse<_i3.UserProfile>> getAllUsers({
    int? page = 0,
    int? size = 20,
    String? sort = 'username',
    String? direction = 'asc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
            #direction: direction,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserProfile>>.value(
            _FakePageResponse_0<_i3.UserProfile>(
          this,
          Invocation.method(
            #getAllUsers,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
              #direction: direction,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserProfile>>);

  @override
  _i5.Future<_i3.UserProfile> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserByUsername,
            [username],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i2.PageResponse<_i3.Friendship>> getFriends({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriends,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.Friendship>>.value(
            _FakePageResponse_0<_i3.Friendship>(
          this,
          Invocation.method(
            #getFriends,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.Friendship>>);

  @override
  _i5.Future<List<_i3.FriendRequest>> getReceivedFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedFriendRequests,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.FriendRequest>>.value(<_i3.FriendRequest>[]),
      ) as _i5.Future<List<_i3.FriendRequest>>);

  @override
  _i5.Future<List<_i3.FriendRequest>> getSentFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentFriendRequests,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.FriendRequest>>.value(<_i3.FriendRequest>[]),
      ) as _i5.Future<List<_i3.FriendRequest>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserFollow>> getFollowing({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserFollow>>.value(
            _FakePageResponse_0<_i3.UserFollow>(
          this,
          Invocation.method(
            #getFollowing,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserFollow>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserFollow>> getFollowers({
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserFollow>>.value(
            _FakePageResponse_0<_i3.UserFollow>(
          this,
          Invocation.method(
            #getFollowers,
            [],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserFollow>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserFollow>> getUserFollowing(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowing,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserFollow>>.value(
            _FakePageResponse_0<_i3.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowing,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserFollow>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserFollow>> getUserFollowers(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowers,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserFollow>>.value(
            _FakePageResponse_0<_i3.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowers,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserFollow>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.Friendship>> getUserFriends(
    String? userId, {
    int? page = 0,
    int? size = 20,
    String? sort = 'createdAt,desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFriends,
          [userId],
          {
            #page: page,
            #size: size,
            #sort: sort,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.Friendship>>.value(
            _FakePageResponse_0<_i3.Friendship>(
          this,
          Invocation.method(
            #getUserFriends,
            [userId],
            {
              #page: page,
              #size: size,
              #sort: sort,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.Friendship>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserProfile>> getDiscoverableUsers({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoverableUsers,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserProfile>>.value(
            _FakePageResponse_0<_i3.UserProfile>(
          this,
          Invocation.method(
            #getDiscoverableUsers,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserProfile>>);

  @override
  _i5.Future<_i2.PageResponse<_i3.UserRelationship>> getAssociatedUsers(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssociatedUsers,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i5.Future<_i2.PageResponse<_i3.UserRelationship>>.value(
            _FakePageResponse_0<_i3.UserRelationship>(
          this,
          Invocation.method(
            #getAssociatedUsers,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i2.PageResponse<_i3.UserRelationship>>);
}

/// A class which mocks [UserCommandClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCommandClient extends _i1.Mock implements _i6.UserCommandClient {
  MockUserCommandClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserProfile> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [userData],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #createUser,
            [userData],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<String> sendFriendRequest(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [userId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #sendFriendRequest,
            [userId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #acceptFriendRequest,
            [requestId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFriendRequest,
          [requestId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #deleteFriendRequest,
            [requestId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> removeFriend(String? friendId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #removeFriend,
            [friendId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> followUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #followUser,
            [userId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> unfollowUser(String? followedId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [followedId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #unfollowUser,
            [followedId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> updateProfile(_i3.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadAvatar(
    List<int>? fileBytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            fileBytes,
            fileName,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              fileBytes,
              fileName,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #deleteAvatar,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteMyAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteMyAccount,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #deleteMyAccount,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}
