// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/state/user_chrome/user_chrome_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i2;
import 'package:wanderer_frontend/data/models/trip_models.dart' as _i5;
import 'package:wanderer_frontend/data/repositories/home_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getCurrentUsername() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUsername,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getCurrentDisplayName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentDisplayName,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getCurrentAvatarUrl() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAvatarUrl,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> refreshUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #refreshUserDetails,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.PageResponse<_i5.Trip>> loadTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i4.Future<_i2.PageResponse<_i5.Trip>>.value(
            _FakePageResponse_0<_i5.Trip>(
          this,
          Invocation.method(
            #loadTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.PageResponse<_i5.Trip>>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Set<String>> getFriendsIds() => (super.noSuchMethod(
        Invocation.method(
          #getFriendsIds,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<Set<String>> getFollowingIds() => (super.noSuchMethod(
        Invocation.method(
          #getFollowingIds,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<_i2.PageResponse<_i5.Trip>> getMyTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i4.Future<_i2.PageResponse<_i5.Trip>>.value(
            _FakePageResponse_0<_i5.Trip>(
          this,
          Invocation.method(
            #getMyTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.PageResponse<_i5.Trip>>);

  @override
  _i4.Future<_i2.PageResponse<_i5.Trip>> getPublicTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i4.Future<_i2.PageResponse<_i5.Trip>>.value(
            _FakePageResponse_0<_i5.Trip>(
          this,
          Invocation.method(
            #getPublicTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.PageResponse<_i5.Trip>>);

  @override
  _i4.Future<dynamic> getMyProfile() => (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
