// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/repositories/trip_detail_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:wanderer_frontend/data/models/auth_models.dart' as _i5;
import 'package:wanderer_frontend/data/models/comment_models.dart' as _i3;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i2;
import 'package:wanderer_frontend/data/models/trip_models.dart' as _i4;
import 'package:wanderer_frontend/data/services/auth_service.dart' as _i10;
import 'package:wanderer_frontend/data/services/comment_service.dart' as _i6;
import 'package:wanderer_frontend/data/services/trip_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComment_1 extends _i1.SmartFake implements _i3.Comment {
  _FakeComment_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrip_2 extends _i1.SmartFake implements _i4.Trip {
  _FakeTrip_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterPendingResponse_3 extends _i1.SmartFake
    implements _i5.RegisterPendingResponse {
  _FakeRegisterPendingResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_4 extends _i1.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentService extends _i1.Mock implements _i6.CommentService {
  MockCommentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.PageResponse<_i3.Comment>> getCommentsByTripId(
    String? tripId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentsByTripId,
          [tripId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i3.Comment>>.value(
            _FakePageResponse_0<_i3.Comment>(
          this,
          Invocation.method(
            #getCommentsByTripId,
            [tripId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i3.Comment>>);

  @override
  _i7.Future<List<_i3.Comment>> getRepliesByCommentId(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRepliesByCommentId,
          [commentId],
        ),
        returnValue: _i7.Future<List<_i3.Comment>>.value(<_i3.Comment>[]),
      ) as _i7.Future<List<_i3.Comment>>);

  @override
  _i7.Future<_i3.Comment> getCommentById(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentById,
          [commentId],
        ),
        returnValue: _i7.Future<_i3.Comment>.value(_FakeComment_1(
          this,
          Invocation.method(
            #getCommentById,
            [commentId],
          ),
        )),
      ) as _i7.Future<_i3.Comment>);

  @override
  _i7.Future<String> addComment(
    String? tripId,
    _i3.CreateCommentRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addComment,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> addReaction(
    String? commentId,
    _i3.AddReactionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReaction,
          [
            commentId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addReaction,
            [
              commentId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> removeReaction(
    String? commentId,
    _i3.AddReactionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeReaction,
          [
            commentId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #removeReaction,
            [
              commentId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);
}

/// A class which mocks [TripService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripService extends _i1.Mock implements _i9.TripService {
  MockTripService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.Trip>> getMyTrips() => (super.noSuchMethod(
        Invocation.method(
          #getMyTrips,
          [],
        ),
        returnValue: _i7.Future<List<_i4.Trip>>.value(<_i4.Trip>[]),
      ) as _i7.Future<List<_i4.Trip>>);

  @override
  _i7.Future<_i4.Trip> getTripById(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [tripId],
        ),
        returnValue: _i7.Future<_i4.Trip>.value(_FakeTrip_2(
          this,
          Invocation.method(
            #getTripById,
            [tripId],
          ),
        )),
      ) as _i7.Future<_i4.Trip>);

  @override
  _i7.Future<_i4.Trip> getPublicTripById(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #getPublicTripById,
          [tripId],
        ),
        returnValue: _i7.Future<_i4.Trip>.value(_FakeTrip_2(
          this,
          Invocation.method(
            #getPublicTripById,
            [tripId],
          ),
        )),
      ) as _i7.Future<_i4.Trip>);

  @override
  _i7.Future<_i2.PageResponse<_i4.Trip>> getAllTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i4.Trip>>.value(
            _FakePageResponse_0<_i4.Trip>(
          this,
          Invocation.method(
            #getAllTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i4.Trip>>);

  @override
  _i7.Future<_i2.PageResponse<_i4.Trip>> getPublicTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i4.Trip>>.value(
            _FakePageResponse_0<_i4.Trip>(
          this,
          Invocation.method(
            #getPublicTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i4.Trip>>);

  @override
  _i7.Future<_i2.PageResponse<_i4.Trip>> getAvailableTrips({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTrips,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i4.Trip>>.value(
            _FakePageResponse_0<_i4.Trip>(
          this,
          Invocation.method(
            #getAvailableTrips,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i4.Trip>>);

  @override
  _i7.Future<List<_i4.Trip>> getUserTrips(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTrips,
          [userId],
        ),
        returnValue: _i7.Future<List<_i4.Trip>>.value(<_i4.Trip>[]),
      ) as _i7.Future<List<_i4.Trip>>);

  @override
  _i7.Future<String> createTrip(_i4.CreateTripRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTrip,
          [request],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createTrip,
            [request],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> updateTrip(
    String? tripId,
    _i4.UpdateTripRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #updateTrip,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> changeVisibility(
    String? tripId,
    _i4.ChangeVisibilityRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeVisibility,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #changeVisibility,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> changeStatus(
    String? tripId,
    _i4.ChangeStatusRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeStatus,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #changeStatus,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> changeSettings(
    String? tripId,
    _i4.ChangeTripSettingsRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeSettings,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #changeSettings,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> toggleDay(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #toggleDay,
          [tripId],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #toggleDay,
            [tripId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteTrip(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [tripId],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #deleteTrip,
            [tripId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> createTripFromPlan(
    String? tripPlanId,
    _i4.TripFromPlanRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTripFromPlan,
          [
            tripPlanId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createTripFromPlan,
            [
              tripPlanId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> sendTripUpdate(
    String? tripId,
    _i4.TripUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTripUpdate,
          [
            tripId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #sendTripUpdate,
            [
              tripId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> createTripPlan(_i4.CreateTripPlanRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTripPlan,
          [request],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createTripPlan,
            [request],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> updateTripPlan(
    String? planId,
    _i4.UpdateTripPlanRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTripPlan,
          [
            planId,
            request,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #updateTripPlan,
            [
              planId,
              request,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteTripPlan(String? planId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTripPlan,
          [planId],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #deleteTripPlan,
            [planId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i2.PageResponse<_i4.TripLocation>> getTripUpdates(
    String? tripId, {
    int? page = 0,
    int? size = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripUpdates,
          [tripId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i4.TripLocation>>.value(
            _FakePageResponse_0<_i4.TripLocation>(
          this,
          Invocation.method(
            #getTripUpdates,
            [tripId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i4.TripLocation>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.RegisterPendingResponse> register(
          _i5.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i7.Future<_i5.RegisterPendingResponse>.value(
            _FakeRegisterPendingResponse_3(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.RegisterPendingResponse>);

  @override
  _i7.Future<_i5.AuthResponse> verifyEmail(_i5.VerifyEmailRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [request],
        ),
        returnValue: _i7.Future<_i5.AuthResponse>.value(_FakeAuthResponse_4(
          this,
          Invocation.method(
            #verifyEmail,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.AuthResponse>);

  @override
  _i7.Future<_i5.AuthResponse> login(_i5.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i7.Future<_i5.AuthResponse>.value(_FakeAuthResponse_4(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.AuthResponse>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> requestPasswordReset(String? email) => (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> changePassword(_i5.PasswordChangeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [request],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentUsername() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUsername,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentDisplayName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentDisplayName,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentAvatarUrl() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAvatarUrl,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> refreshUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #refreshUserDetails,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> refreshAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshAccessToken,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isTokenExpired() => (super.noSuchMethod(
        Invocation.method(
          #isTokenExpired,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}
