// Mocks generated by Mockito 5.4.6 from annotations
// in wanderer_frontend/test/state/trip_detail/trip_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:wanderer_frontend/core/constants/enums.dart' as _i10;
import 'package:wanderer_frontend/data/client/query/promotion_query_client.dart'
    as _i11;
import 'package:wanderer_frontend/data/models/achievement_models.dart' as _i13;
import 'package:wanderer_frontend/data/models/comment_models.dart' as _i8;
import 'package:wanderer_frontend/data/models/domain/location_update_result.dart'
    as _i4;
import 'package:wanderer_frontend/data/models/responses/page_response.dart'
    as _i2;
import 'package:wanderer_frontend/data/models/trip_models.dart' as _i3;
import 'package:wanderer_frontend/data/models/user_models.dart' as _i5;
import 'package:wanderer_frontend/data/repositories/trip_detail_repository.dart'
    as _i6;
import 'package:wanderer_frontend/data/services/achievement_service.dart'
    as _i12;
import 'package:wanderer_frontend/data/services/user_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrip_1 extends _i1.SmartFake implements _i3.Trip {
  _FakeTrip_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationUpdateResult_2 extends _i1.SmartFake
    implements _i4.LocationUpdateResult {
  _FakeLocationUpdateResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTripPromotion_3 extends _i1.SmartFake implements _i3.TripPromotion {
  _FakeTripPromotion_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_4 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TripDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripDetailRepository extends _i1.Mock
    implements _i6.TripDetailRepository {
  MockTripDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.PageResponse<_i8.Comment>> loadComments(
    String? tripId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadComments,
          [tripId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i8.Comment>>.value(
            _FakePageResponse_0<_i8.Comment>(
          this,
          Invocation.method(
            #loadComments,
            [tripId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i8.Comment>>);

  @override
  _i7.Future<_i3.Trip> getTripById(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [tripId],
        ),
        returnValue: _i7.Future<_i3.Trip>.value(_FakeTrip_1(
          this,
          Invocation.method(
            #getTripById,
            [tripId],
          ),
        )),
      ) as _i7.Future<_i3.Trip>);

  @override
  _i7.Future<List<_i8.Comment>> loadReplies(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadReplies,
          [commentId],
        ),
        returnValue: _i7.Future<List<_i8.Comment>>.value(<_i8.Comment>[]),
      ) as _i7.Future<List<_i8.Comment>>);

  @override
  _i7.Future<List<_i8.Reaction>> loadReactions(_i8.Comment? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadReactions,
          [comment],
        ),
        returnValue: _i7.Future<List<_i8.Reaction>>.value(<_i8.Reaction>[]),
      ) as _i7.Future<List<_i8.Reaction>>);

  @override
  _i7.Future<String> addComment(
    String? tripId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            tripId,
            message,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #addComment,
            [
              tripId,
              message,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> addReply(
    String? tripId,
    String? parentCommentId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReply,
          [
            tripId,
            parentCommentId,
            message,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #addReply,
            [
              tripId,
              parentCommentId,
              message,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> addReaction(
    String? commentId,
    _i8.ReactionType? reactionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReaction,
          [
            commentId,
            reactionType,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeReaction(
    String? commentId,
    _i8.ReactionType? reactionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeReaction,
          [
            commentId,
            reactionType,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> changeTripStatus(
    String? tripId,
    _i10.TripStatus? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTripStatus,
          [
            tripId,
            newStatus,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #changeTripStatus,
            [
              tripId,
              newStatus,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> changeTripVisibility(
    String? tripId,
    _i10.Visibility? newVisibility,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTripVisibility,
          [
            tripId,
            newVisibility,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #changeTripVisibility,
            [
              tripId,
              newVisibility,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> toggleDay(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #toggleDay,
          [tripId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #toggleDay,
            [tripId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> changeTripSettings(
    String? tripId,
    bool? automaticUpdates,
    int? updateRefresh, {
    _i10.TripModality? tripModality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTripSettings,
          [
            tripId,
            automaticUpdates,
            updateRefresh,
          ],
          {#tripModality: tripModality},
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #changeTripSettings,
            [
              tripId,
              automaticUpdates,
              updateRefresh,
            ],
            {#tripModality: tripModality},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteTrip(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [tripId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #deleteTrip,
            [tripId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> getCurrentUsername() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUsername,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentDisplayName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentDisplayName,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentAvatarUrl() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAvatarUrl,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> refreshUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #refreshUserDetails,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.PageResponse<_i3.TripLocation>> loadTripUpdates(
    String? tripId, {
    int? page = 0,
    int? size = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTripUpdates,
          [tripId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i3.TripLocation>>.value(
            _FakePageResponse_0<_i3.TripLocation>(
          this,
          Invocation.method(
            #loadTripUpdates,
            [tripId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i3.TripLocation>>);

  @override
  _i7.Future<_i4.LocationUpdateResult> sendTripUpdate(
    String? tripId, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTripUpdate,
          [tripId],
          {#message: message},
        ),
        returnValue: _i7.Future<_i4.LocationUpdateResult>.value(
            _FakeLocationUpdateResult_2(
          this,
          Invocation.method(
            #sendTripUpdate,
            [tripId],
            {#message: message},
          ),
        )),
      ) as _i7.Future<_i4.LocationUpdateResult>);

  @override
  _i7.Future<_i4.LocationUpdateResult> sendLifecycleUpdate(
    String? tripId, {
    required _i10.TripUpdateType? updateType,
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLifecycleUpdate,
          [tripId],
          {
            #updateType: updateType,
            #message: message,
          },
        ),
        returnValue: _i7.Future<_i4.LocationUpdateResult>.value(
            _FakeLocationUpdateResult_2(
          this,
          Invocation.method(
            #sendLifecycleUpdate,
            [tripId],
            {
              #updateType: updateType,
              #message: message,
            },
          ),
        )),
      ) as _i7.Future<_i4.LocationUpdateResult>);
}

/// A class which mocks [PromotionQueryClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromotionQueryClient extends _i1.Mock
    implements _i11.PromotionQueryClient {
  MockPromotionQueryClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.PromotedTrip>> getPromotedTrips() => (super.noSuchMethod(
        Invocation.method(
          #getPromotedTrips,
          [],
        ),
        returnValue:
            _i7.Future<List<_i3.PromotedTrip>>.value(<_i3.PromotedTrip>[]),
      ) as _i7.Future<List<_i3.PromotedTrip>>);

  @override
  _i7.Future<_i3.TripPromotion> getTripPromotion(String? tripId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripPromotion,
          [tripId],
        ),
        returnValue: _i7.Future<_i3.TripPromotion>.value(_FakeTripPromotion_3(
          this,
          Invocation.method(
            #getTripPromotion,
            [tripId],
          ),
        )),
      ) as _i7.Future<_i3.TripPromotion>);
}

/// A class which mocks [AchievementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementService extends _i1.Mock
    implements _i12.AchievementService {
  MockAchievementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i13.Achievement>> getAllAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAchievements,
          [],
        ),
        returnValue:
            _i7.Future<List<_i13.Achievement>>.value(<_i13.Achievement>[]),
      ) as _i7.Future<List<_i13.Achievement>>);

  @override
  _i7.Future<List<_i13.UserAchievement>> getMyAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyAchievements,
          [],
        ),
        returnValue: _i7.Future<List<_i13.UserAchievement>>.value(
            <_i13.UserAchievement>[]),
      ) as _i7.Future<List<_i13.UserAchievement>>);

  @override
  _i7.Future<List<_i13.UserAchievement>> getUserAchievements(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAchievements,
          [userId],
        ),
        returnValue: _i7.Future<List<_i13.UserAchievement>>.value(
            <_i13.UserAchievement>[]),
      ) as _i7.Future<List<_i13.UserAchievement>>);

  @override
  _i7.Future<List<_i13.UserAchievement>> getTripAchievements(String? tripId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripAchievements,
          [tripId],
        ),
        returnValue: _i7.Future<List<_i13.UserAchievement>>.value(
            <_i13.UserAchievement>[]),
      ) as _i7.Future<List<_i13.UserAchievement>>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i14.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.UserProfile> getMyProfile() => (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
        ),
        returnValue: _i7.Future<_i5.UserProfile>.value(_FakeUserProfile_4(
          this,
          Invocation.method(
            #getMyProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i5.UserProfile>);

  @override
  _i7.Future<_i5.UserProfile> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i7.Future<_i5.UserProfile>.value(_FakeUserProfile_4(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i7.Future<_i5.UserProfile>);

  @override
  _i7.Future<_i5.UserProfile> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i7.Future<_i5.UserProfile>.value(_FakeUserProfile_4(
          this,
          Invocation.method(
            #getUserByUsername,
            [username],
          ),
        )),
      ) as _i7.Future<_i5.UserProfile>);

  @override
  _i7.Future<_i2.PageResponse<_i5.Friendship>> getFriends({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriends,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.Friendship>>.value(
            _FakePageResponse_0<_i5.Friendship>(
          this,
          Invocation.method(
            #getFriends,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.Friendship>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserFollow>> getFollowing({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserFollow>>.value(
            _FakePageResponse_0<_i5.UserFollow>(
          this,
          Invocation.method(
            #getFollowing,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserFollow>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserFollow>> getFollowers({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserFollow>>.value(
            _FakePageResponse_0<_i5.UserFollow>(
          this,
          Invocation.method(
            #getFollowers,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserFollow>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserFollow>> getUserFollowing(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowing,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserFollow>>.value(
            _FakePageResponse_0<_i5.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowing,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserFollow>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserFollow>> getUserFollowers(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowers,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserFollow>>.value(
            _FakePageResponse_0<_i5.UserFollow>(
          this,
          Invocation.method(
            #getUserFollowers,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserFollow>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.Friendship>> getUserFriends(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFriends,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.Friendship>>.value(
            _FakePageResponse_0<_i5.Friendship>(
          this,
          Invocation.method(
            #getUserFriends,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.Friendship>>);

  @override
  _i7.Future<List<_i5.FriendRequest>> getReceivedFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedFriendRequests,
          [],
        ),
        returnValue:
            _i7.Future<List<_i5.FriendRequest>>.value(<_i5.FriendRequest>[]),
      ) as _i7.Future<List<_i5.FriendRequest>>);

  @override
  _i7.Future<List<_i5.FriendRequest>> getSentFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentFriendRequests,
          [],
        ),
        returnValue:
            _i7.Future<List<_i5.FriendRequest>>.value(<_i5.FriendRequest>[]),
      ) as _i7.Future<List<_i5.FriendRequest>>);

  @override
  _i7.Future<String> sendFriendRequest(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [userId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #sendFriendRequest,
            [userId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #acceptFriendRequest,
            [requestId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFriendRequest,
          [requestId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #deleteFriendRequest,
            [requestId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> removeFriend(String? friendId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #removeFriend,
            [friendId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> followUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #followUser,
            [userId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> unfollowUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [userId],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #unfollowUser,
            [userId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> updateProfile(_i5.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> uploadAvatar(
    List<int>? fileBytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            fileBytes,
            fileName,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              fileBytes,
              fileName,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #deleteAvatar,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> deleteMyAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteMyAccount,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #deleteMyAccount,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserProfile>> getDiscoverableUsers({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoverableUsers,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserProfile>>.value(
            _FakePageResponse_0<_i5.UserProfile>(
          this,
          Invocation.method(
            #getDiscoverableUsers,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserProfile>>);

  @override
  _i7.Future<_i2.PageResponse<_i5.UserRelationship>> getAssociatedUsers(
    String? userId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssociatedUsers,
          [userId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i7.Future<_i2.PageResponse<_i5.UserRelationship>>.value(
            _FakePageResponse_0<_i5.UserRelationship>(
          this,
          Invocation.method(
            #getAssociatedUsers,
            [userId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i7.Future<_i2.PageResponse<_i5.UserRelationship>>);
}
